Adds check/display change if root, shows return value if non-zero.

diff --git a/prompts/gomacbp b/prompts/gomacbp
--- a/prompts/gomacbp
+++ b/prompts/gomacbp
@@ -21,7 +21,19 @@ source "${PROMPTDIR}/directory/_p_tildepwd"
 source "${PROMPTDIR}/machine/_p_powerconnected"
 source "${PROMPTDIR}/machine/_p_powerpercent"
 
+if [ "${_p_uid0}" == "true" ]
+then
+    export _p_usercolour="${_pc_b_red}"
+else
+    export _p_usercolour="${_pc_b_gray}"
+fi
 function prompt_command () {
+    _p_retval=$? # capture the return value before you change it w/prompt
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
     _p_xtermtitle # generates the _p_TITLEBAR variable
 }
 
@@ -48,9 +60,11 @@ PS1="${PS1}${_pc_b_gray}-${_pc_b_blue}-("
 PS1="${PS1}${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
 PS1="${PS1}${_pc_nocolour} "
 # User @ Hostname:
-PS1="${PS1}${_pc_b_gray}\u${_pc_b_blue}@${_pc_b_gray}\h"
+PS1="${PS1}${_p_usercolour}\u${_pc_b_blue}@${_pc_b_gray}\h"
 PS1="${PS1}${_pc_b_blue})-${_pc_b_gray}-"
-PS1="${PS1}\$"
+PS1="${PS1}${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
+PS1="${PS1}${_pc_nocolour}"
+PS1="${PS1}${_pc_b_gray}\$"
 PS1="${PS1}${_pc_nocolour} "
 
 export PS1
