Add ephemeral disk-free stoplight to both prompts (and cleanup).

diff --git a/prompts/greeny b/prompts/greeny
--- a/prompts/greeny
+++ b/prompts/greeny
@@ -9,17 +9,30 @@
 # Named for its dominant colour.  No git support.
 
 echo "Prompt Title: greeny"
-echo "Includes:     user@host, history, tty, PWD, newline, time (no git)"
+echo "Includes:     user@host, history, PWD, newline, time (no git)"
 echo "For:          a dark background (colours don't work well on Mac)"
 echo "Requires:     "
 
 # Get the components we need:
 source "${PROMPTDIR}/_p_colours" # get colours into the environment
 source "${PROMPTDIR}/machine/_p_shorttty"
+source "${PROMPTDIR}/machine/_p_df_sl"
+source "${PROMPTDIR}/directory/_p_git"
 source "${PROMPTDIR}/directory/_p_xtermtitle"
 source "${PROMPTDIR}/directory/_p_tildepwd"
 
 _p_xtermtitle # generates the _p_TITLEBAR variable
+
+prompt_command () {
+    _p_retval=$? # capture the return value before you change it
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
+}
+
+PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "
 
 PS1=""
 PS1="${PS1}${_p_TITLEBAR}"
@@ -40,14 +53,22 @@ PS1="${PS1}${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_green}("
 PS1="${PS1}${_pc_b_gray}\$(_p_shorttty)"
 PS1="${PS1}${_pc_b_black}:"
 PS1="${PS1}${_pc_nocolour}${_pc_green}\$(_p_tildepwd)"
+PS1="${PS1} ${_pc_italics}\$(_p_git)${_pc_nocolour}"
 PS1="${PS1}${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_black}"
 PS1="${PS1}\n" # ------------------------------------------
 PS1="${PS1}${_pc_b_black}-${_pc_green}-${_pc_b_green}("
 PS1="${PS1}${_pc_b_green}\D{%H%M}"
 PS1="${PS1}${_pc_nocolour}${_pc_green}:"
-PS1="${PS1}${_pc_b_gray}\$"
+PS1="${PS1}${_pc_b_gray}\\\$"
+PS1="${PS1}${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
+PS1="${PS1}${_pc_nocolour}"
 PS1="${PS1}${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_black}"
 PS1="${PS1}${_pc_nocolour} "
+PS1="${PS1}\[\$(
+    tput sc
+    echo -en \"   ${_c_darkgray}\$(_p_df_sl)  \$(date +%m-%d-%H%M)${_c_nocolour}\"
+    tput rc
+)\]"
 
 export PS1
 
