Add return value and minor clean-up.

diff --git a/prompts/one-long-trad b/prompts/one-long-trad
--- a/prompts/one-long-trad
+++ b/prompts/one-long-trad
@@ -23,8 +23,22 @@ source "${PROMPTDIR}/directory/_p_tildepwd"
 source "${PROMPTDIR}/machine/_p_powerconnected"
 source "${PROMPTDIR}/machine/_p_powerpercent"
 
+_p_xtermtitle # generates the _p_TITLEBAR variable
+
 prompt_command () {
-    _p_xtermtitle # generates the _p_TITLEBAR variable
+    _p_retval=$? # capture the return value before you change it
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
+    if command git status >/dev/null 2>&1
+    then
+        # we're in a git repo:
+        git_out="($(_p_git))"
+    else
+        git_out=""
+    fi
 }
 
 PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "
@@ -36,7 +50,8 @@ PS1="${PS1}${_p_nocolour} "
 PS1="${PS1}${_pc_b_green}\u@\h"
 PS1="${PS1}${_p_nocolour}:"
 PS1="${PS1}${_pc_b_blue}\$(_p_tildepwd)"
-PS1="${PS1}${_pc_nocolour}(\$(_p_git))"
+PS1="${PS1}${_pc_nocolour}\${git_out}"
+PS1="${PS1}${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
 PS1="${PS1}\$ "
 
 export PS1
diff --git a/prompts/onetwored b/prompts/onetwored
--- a/prompts/onetwored
+++ b/prompts/onetwored
@@ -31,9 +31,17 @@ source "${PROMPTDIR}/directory/_p_xtermtitle"
 source "${PROMPTDIR}/machine/_p_uptime"
 source "${PROMPTDIR}/machine/_p_upseconds"
 
+# shellcheck disable=SC2034  # appears unused ...
 minRemainingWidth=50
 
 prompt_command () {
+    _p_retval=$? # capture the return value before you change it
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
+
     _p_displayGit="$(_p_git)"
     _p_tilde="~"
     # on Linux/Bash4 we need "\~", on Mac/Bash3 we need "~" in this
@@ -45,6 +53,7 @@ prompt_command () {
     then
         p_show_up=0
     else
+        # shellcheck disable=SC2034  # appears unused ...
         p_show_up=1
     fi
     _p_xtermtitle # generates the _p_TITLEBAR variable
@@ -54,6 +63,7 @@ PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "
 
 PS1=""
 PS1="${PS1}${_p_TITLEBAR}"
+# shellcheck disable=SC1001  # "This \u will be a regular 'u' in this context"
 PS1="${PS1}\$(
 if (( p_show_up == 0 ))
 then
@@ -101,6 +111,8 @@ else   # the one line version
     fi
     echo -en \"${_pc_darkgray}|${_pc_nocolour}\"
     echo -en \"${_pc_red}\u${_pc_darkgray}@${_pc_red}\h\"
+    echo -en \"${_pc_bg_gray}${_pc_b_red}\${_p_retval}\"
+    echo -en \"${_pc_nocolour}\"
     echo -en \"${_pc_darkgray}\$\"
     echo -en \"${_pc_b_red})-${_pc_red}-${_pc_darkgray}-\"
     echo -e  \"${_pc_nocolour} \";
