Added return value, improved git display.

diff --git a/prompts/one-short b/prompts/one-short
--- a/prompts/one-short
+++ b/prompts/one-short
@@ -23,6 +23,13 @@ source "${PROMPTDIR}/machine/_p_powerpercent"
 source "${PROMPTDIR}/machine/_p_df_stoplight"
 
 prompt_command () {
+    _p_retval=$? # capture the return value before you change it
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
+
     _p_xtermtitle # generates the _p_TITLEBAR variable
     local tmp
     tmp=$(_p_git)
@@ -30,7 +37,7 @@ prompt_command () {
     then
         _p_git_output=""
     else
-        _p_git_output="${tmp}"
+        _p_git_output="◆${tmp}"
     fi
 }
 
@@ -47,8 +54,8 @@ PS1="${PS1}\$(_p_df_stoplight)"
 PS1="${PS1}${_pc_b_gray}\u${_pc_b_black}@${_pc_b_gray}\h"
 PS1="${PS1}${_p_nocolour}:"
 PS1="${PS1}${_pc_nocolour}\$(_p_shortpwd 15)"
-PS1="${PS1}${_pc_b_red}≡"
 PS1="${PS1}${_pc_nocolour}\${_p_git_output}"
+PS1="${PS1}${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
 PS1="${PS1}${_pc_b_yellow}\$${_pc_nocolour} "
 
 export PS1
