(Mostly) changing 'PS1="${PS1}' to 'PS1+="'.

diff --git a/prompts/onetwonofill b/prompts/onetwonofill
--- a/prompts/onetwonofill
+++ b/prompts/onetwonofill
@@ -12,7 +12,7 @@
 # fill - which significantly reduces the complexity and no longer requires
 # the maintainenance of two different versions.
 
-echo "Prompt Title: onetwopowernofill"
+echo "Prompt Title: onetwonofill"
 echo "Includes:     pwd, git, power, user@host"
 echo "For:          a dark background"
 echo "Requires:     git"
@@ -26,6 +26,13 @@ source "${PROMPTDIR}/machine/_p_powerpercent"
 minRemainingWidth=50
 
 prompt_command () {
+    _p_retval=$? # capture the return value before you change it
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
+
     # set some variables to be displayed later
     _p_displayGit="$(_p_git)"
     _p_displayPower="($(_p_powerconnected)$(_p_powerpercent)%)"
@@ -39,8 +46,8 @@ prompt_command () {
 PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "
 
 PS1=""
-PS1="${PS1}${_p_TITLEBAR}"
-PS1="${PS1}\$(
+PS1+="${_p_TITLEBAR}"
+PS1+="\$(
 remainingWidth=\$(( COLUMNS - \${#_p_displayPower} - \${#_p_dir} - \${#_p_displayGit} - \$(echo "\u@\h" | wc -c) - 3 ))
 
 echo -en \"${_pc_b_gray}\${_p_displayPower}${_pc_nocolour}\"
@@ -58,7 +65,9 @@ else   # the one line version
     echo -en \"${_pc_b_gray}|\"
 fi
 echo -en \"${_pc_nocolour}\u${_pc_b_yellow}@${_pc_nocolour}\h\"
-echo -e  \"${_pc_b_yellow}\$${_pc_nocolour} \";
+echo -en \"${_pc_bg_gray}${_pc_b_red}\${_p_retval}\"
+echo -en \"${_pc_nocolour}\"
+echo -e  \"${_pc_b_yellow}\\\$${_pc_nocolour} \";
 )"
 
 export PS1
diff --git a/prompts/sa b/prompts/sa
--- a/prompts/sa
+++ b/prompts/sa
@@ -7,7 +7,7 @@
 # shellcheck disable=SC2154  # "referenced but not assigned"
 
 echo "Prompt Title: sa"
-echo "Includes:     git status, colour PWD, newline, battery, user@host"
+echo "Includes:     return value, git status, colour PWD, newline, battery, user@host"
 echo "For:          a dark background"
 echo "Requires:     git"
 
@@ -18,33 +18,41 @@ source "${PROMPTDIR}/directory/_p_colourslashpwd"
 source "${PROMPTDIR}/machine/_p_powerconnected"
 source "${PROMPTDIR}/machine/_p_powerpercent"
 
-PS1="${_pc_b_gray}-"
-PS1="${PS1}${_pc_b_blue}-"
-PS1="${PS1}${_pc_b_purple}\$(_p_git)"
-PS1="${PS1}${_pc_b_blue}-"
-PS1="${PS1}${_pc_b_gray}-"
-PS1="${PS1}-"
-PS1="${PS1}${_pc_b_blue}-("
-PS1="${PS1}\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_yellow} \${_pc_nocolour})"
-PS1="${PS1}${_pc_b_blue})-"
-PS1="${PS1}${_pc_b_gray}-"
-PS1="${PS1}${_pc_nocolour}"
-PS1="${PS1}\n"                  # newline
-PS1="${PS1}${_pc_b_gray}-"
-PS1="${PS1}${_pc_b_blue}-("
+# If PROMPT_COMMAND or prompt_command is ever added to this prompt,
+# capturing the return value (_p_retval below) needs to move into that.
+
+PS1=""
+PS1+="${_pc_bg_gray}${_pc_b_red}"
+PS1+="\$( _p_retval=\$? ; if [ \${_p_retval} -gt 0 ]; then echo \"\${_p_retval}\"; fi )"
+PS1+="${_pc_nocolour}"
+PS1+="${_p_TITLEBAR}"
+PS1+="${_pc_b_gray}-"
+PS1+="${_pc_b_blue}-"
+PS1+="${_pc_b_purple}\$(_p_git)"
+PS1+="${_pc_b_blue}-"
+PS1+="${_pc_b_gray}-"
+PS1+="-"
+PS1+="${_pc_b_blue}-("
+PS1+="\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_yellow} \${_pc_nocolour})"
+PS1+="${_pc_b_blue})-"
+PS1+="${_pc_b_gray}-"
+PS1+="${_pc_nocolour}"
+PS1+="\n"                  # newline
+PS1+="${_pc_b_gray}-"
+PS1+="${_pc_b_blue}-("
 if [ "${_p_has_battery}" == "true" ]
 then
-    PS1="${PS1}${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
-    PS1="${PS1}${_pc_nocolour} "
+    PS1+="${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
+    PS1+="${_pc_nocolour} "
 else
-    PS1="${PS1}${_pc_nocolour}"
+    PS1+="${_pc_nocolour}"
 fi
 # User @ Hostname:
-PS1="${PS1}${_pc_b_gray}\u${_pc_b_blue}@${_pc_b_gray}\h"
-PS1="${PS1}${_pc_b_blue})-"
-PS1="${PS1}${_pc_b_gray}-"
-PS1="${PS1}\$"
-PS1="${PS1}${_pc_nocolour} "
+PS1+="${_pc_b_gray}\u${_pc_b_blue}@${_pc_b_gray}\h"
+PS1+="${_pc_b_blue})-"
+PS1+="${_pc_b_gray}-"
+PS1+="\\\$"
+PS1+="${_pc_nocolour} "
 
 export PS1
 
diff --git a/prompts/slim b/prompts/slim
--- a/prompts/slim
+++ b/prompts/slim
@@ -20,8 +20,15 @@ source "${PROMPTDIR}/directory/_p_xtermtitle"
 source "${PROMPTDIR}/directory/_p_git"
 source "${PROMPTDIR}/directory/_p_tildepwd"
 
+_p_xtermtitle # generates the _p_TITLEBAR variable
+
 prompt_command () {
-    _p_xtermtitle # generates the _p_TITLEBAR variable
+    _p_retval=$? # capture the return value before you change it
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
 }
 
 PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "
@@ -29,44 +36,46 @@ PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "
 PS1=""
 if [ "${_p_in_tmux}" == "true" ]
 then
-    PS1="${PS1}[t]"
+    PS1+="[t]"
 fi
 if [ "${_p_in_screen}" == "true" ]
 then
-    PS1="${PS1}[s]"
+    PS1+="[s]"
 fi
-PS1="${PS1}${_p_TITLEBAR}"
-PS1="${PS1}${_pc_b_cyan}"
-PS1="${PS1}["
-PS1="${PS1}${_pc_b_yellow}"
-PS1="${PS1}\$(_p_tildepwd)"
-PS1="${PS1}${_pc_b_cyan}"
-PS1="${PS1}]"
-PS1="${PS1}${_pc_nocolour}"
-PS1="${PS1} "
-PS1="${PS1}${_pc_b_yellow}"
-PS1="${PS1}\$(_p_git)"
-PS1="${PS1}${_pc_nocolour}"
-PS1="${PS1}\n"                           # newline
-PS1="${PS1}${_pc_b_cyan}"
-PS1="${PS1}["
-PS1="${PS1}${_pc_b_purple}"
-PS1="${PS1}\$(_p_powerconnected)"
-PS1="${PS1}\$(_p_powerpercent)"
-PS1="${PS1}%"
-PS1="${PS1}${_pc_b_cyan}"
-PS1="${PS1}]"
-PS1="${PS1}${_pc_nocolour}"
-PS1="${PS1} "
-PS1="${PS1}${_pc_b_purple}"
-PS1="${PS1}\u"
-PS1="${PS1}${_pc_b_cyan}"
-PS1="${PS1}@"
-PS1="${PS1}${_pc_b_purple}"
-PS1="${PS1}\h"
-PS1="${PS1}${_pc_b_gray}"
-PS1="${PS1}\$"
-PS1="${PS1}${_pc_nocolour} "
+PS1+="${_p_TITLEBAR}"
+PS1+="${_pc_b_cyan}"
+PS1+="["
+PS1+="${_pc_b_yellow}"
+PS1+="\$(_p_tildepwd)"
+PS1+="${_pc_b_cyan}"
+PS1+="]"
+PS1+="${_pc_nocolour}"
+PS1+=" "
+PS1+="${_pc_b_yellow}"
+PS1+="\$(_p_git)"
+PS1+="${_pc_nocolour}"
+PS1+="\n"                           # newline
+PS1+="${_pc_b_cyan}"
+PS1+="["
+PS1+="${_pc_b_purple}"
+PS1+="\$(_p_powerconnected)"
+PS1+="\$(_p_powerpercent)"
+PS1+="%"
+PS1+="${_pc_b_cyan}"
+PS1+="]"
+PS1+="${_pc_nocolour}"
+PS1+=" "
+PS1+="${_pc_b_purple}"
+PS1+="\u"
+PS1+="${_pc_b_cyan}"
+PS1+="@"
+PS1+="${_pc_b_purple}"
+PS1+="\h"
+PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
+PS1+="${_pc_nocolour}"
+PS1+="${_pc_b_gray}"
+PS1+="\\\$"
+PS1+="${_pc_nocolour} "
 
 export PS1
 
