Adds check/display change if root, shows return value if non-zero.

diff --git a/prompts/purple b/prompts/purple
--- a/prompts/purple
+++ b/prompts/purple
@@ -21,7 +21,13 @@ source "${PROMPTDIR}/directory/_p_git"
 source "${PROMPTDIR}/directory/_p_tildepwd"
 
 function prompt_command () {
+    _p_retval=$? # capture the return value before you change it
     _p_xtermtitle # generates the _p_TITLEBAR variable
+    if (( _p_retval == 0 ))
+    then
+        # disappear the return value if it's zero
+        _p_retval=""
+    fi
 }
 
 export PROMPT_COMMAND=prompt_command
@@ -56,7 +62,8 @@ PS1="${PS1}${_pc_b_purple}"
 PS1="${PS1}\h"
 PS1="${PS1}${_pc_purple}"
 PS1="${PS1}]"
-PS1="${PS1}${_pc_b_gray}"
+PS1="${PS1}${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
+PS1="${PS1}${_pc_nocolour}${_pc_b_gray}"
 PS1="${PS1}\$"
 PS1="${PS1}${_pc_nocolour} "
 
